defmodule GameArchiveWeb.Router do
  use GameArchiveWeb, :router

  import GameArchiveWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {GameArchiveWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GameArchiveWeb do
    pipe_through :browser

    # generated by phx.gen.new
    get "/", PageController, :home

    # no need for these, see the macro below
    # i added these to match phx.gen.html Games
    # get "/games", GameController, :index # :index was auto-gen'd, list_games
    # get "/game/:id", GameController, :show # :show was also auto-gen'd, get_game!

    # NOTE: this is a powerful macro that generates a lot of RESTful routes:
    # https://hexdocs.pm/phoenix/1.7.14/Phoenix.Router.html#resources/4
    resources "/games", GameController
    # by default, creates all of these:
    # can use :only option to limit it
    # GET /games => :index
    # GET /games/new => :new
    # POST /games => :create
    # GET /games/:id => :show
    # GET /games/:id/edit => :edit
    # PATCH /games/:id => :update
    # PUT /games/:id => :update
    # DELETE /games/:id => :delete

    get "/games/:id/:title", GameController, :show # with title slug

   resources "/lists", ListController
  end

  # Other scopes may use custom stacks.
  # scope "/api", GameArchiveWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:game_archive, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: GameArchiveWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", GameArchiveWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    live_session :redirect_if_user_is_authenticated,
      on_mount: [{GameArchiveWeb.UserAuth, :redirect_if_user_is_authenticated}] do
      live "/users/register", UserRegistrationLive, :new
      live "/users/log_in", UserLoginLive, :new
      live "/users/reset_password", UserForgotPasswordLive, :new
      live "/users/reset_password/:token", UserResetPasswordLive, :edit
    end

    post "/users/log_in", UserSessionController, :create
  end

  scope "/", GameArchiveWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :require_authenticated_user,
      on_mount: [{GameArchiveWeb.UserAuth, :ensure_authenticated}] do
      live "/users/settings", UserSettingsLive, :edit
      live "/users/settings/confirm_email/:token", UserSettingsLive, :confirm_email
    end
  end

  scope "/", GameArchiveWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete

    live_session :current_user,
      on_mount: [{GameArchiveWeb.UserAuth, :mount_current_user}] do
      live "/users/confirm/:token", UserConfirmationLive, :edit
      live "/users/confirm", UserConfirmationInstructionsLive, :new
    end
  end
end
